version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysql-data:/var/lib/mysql
    networks: [appnet]

  # Single-node Kafka (KRaft) â€” no Zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8089:8080"
    depends_on:
      kafka:
        condition: service_healthy
    networks: [appnet]

  user-service:
    build: ./user-service
    environment:
      # DB
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/usersdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Eureka off (we're not running Eureka here)
      EUREKA_CLIENT_ENABLED: "false"
      # JWT
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_AUDIENCE: rewards-platform
      SECURITY_JWT_ISSUER: user-service
      # Server port
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks: [appnet]

  transaction-service:
    build: ./Transaction-Service
    environment:
      # DB
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/txdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TX_KAFKA_TOPIC_CREATED: transaction.created.v1
      # Outbox
      TX_OUTBOX_BATCH_SIZE: 50
      TX_OUTBOX_MAX_RETRIES: 5
      TX_OUTBOX_PUBLISH_INTERVAL_MS: 1000
      # JWT (must match user-service)
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_AUDIENCE: rewards-platform
      SECURITY_JWT_ISSUER: user-service
      # Turn off Eureka
      EUREKA_CLIENT_ENABLED: "false"
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks: [appnet]

  reward-service:
    build: ./rewards-service
    environment:
      # DB
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rewardsdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REARDS_TOPIC: transaction.created.v1
      # JWT (needed for user-facing endpoints)
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_AUDIENCE: rewards-platform
      SECURITY_JWT_ISSUER: user-service
      # Turn off Eureka
      EUREKA_CLIENT_ENABLED: "false"
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks: [appnet]

networks:
  appnet:

volumes:
  mysql-data:
